export interface Era {
  id: string;
  title: string;
  emoji: string;
  planet: string;
  planetColor: string;
  planetRing?: string;
  subtitle: string;
  description: string;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  achievements: string[];
  images: string[];
}

export const eras: Era[] = [
  {
    id: 'college-journey',
    title: 'College Journey',
    emoji: '🎓',
    planet: 'Terra Academia',
    planetColor: '#3b82f6',
    planetRing: '#93c5fd',
    subtitle: 'Where it all began — from curiosity to code',
    description:
      'Sathyabama Institute of Science and Technology was where a curious mind found its calling. From learning the fundamentals of computer science to building projects that actually worked, college laid the foundation for everything that followed.',
    color: '#60a5fa',
    gradientFrom: '#2563eb',
    gradientTo: '#60a5fa',
    achievements: [
      'B.Tech in Computer Science & Engineering from Sathyabama Institute',
      'Built strong foundations in DSA, Java, and Python',
      'Developed projects that solved real-world problems',
      'Class XII from Loyola Academy | Class X from Don Bosco, Bandel',
    ],
    images: [],
  },
  {
    id: 'leadership',
    title: 'Leadership & Clubs',
    emoji: '👑',
    planet: 'Regalia Prime',
    planetColor: '#eab308',
    planetRing: '#fde047',
    subtitle: 'Leading from the front',
    description:
      "Being president of the Microsoft Club and CS Club wasn't just a title — it was a responsibility. Leading teams, organizing workshops, mentoring juniors, and building a community of passionate tech enthusiasts shaped my understanding of what it means to lead.",
    color: '#facc15',
    gradientFrom: '#ca8a04',
    gradientTo: '#facc15',
    achievements: [
      'Microsoft Club President',
      'CS Club President',
      'Mentored junior students and organized workshops',
      'Built a thriving tech community on campus',
    ],
    images: [],
  },
  {
    id: 'college-fests',
    title: 'College Fests',
    emoji: '🎉',
    planet: 'Festivus',
    planetColor: '#d946ef',
    subtitle: 'Where work met celebration',
    description:
      "College fests were the perfect blend of creativity, teamwork, and pure fun. From organizing tech events to participating in cultural competitions, these experiences taught leadership and the art of bringing people together.",
    color: '#e879f9',
    gradientFrom: '#a855f7',
    gradientTo: '#e879f9',
    achievements: [
      'Organized and led college tech fests',
      'Cultural event participation and wins',
      'Team coordination and event management',
      'Created memorable experiences for peers',
    ],
    images: [],
  },
  {
    id: 'content-writing',
    title: 'Content Writing',
    emoji: '✍️',
    planet: 'Lexicon',
    planetColor: '#f59e0b',
    subtitle: 'Turning thoughts into words that matter',
    description:
      'Words became my first medium of expression. Whether it was blogs, articles, or social media content, this era sharpened my ability to communicate complex ideas simply — a skill that later proved invaluable in technical documentation.',
    color: '#f59e0b',
    gradientFrom: '#d97706',
    gradientTo: '#fbbf24',
    achievements: [
      'Published articles and blog posts',
      'Content strategy for college publications',
      'Technical writing and documentation',
      'Storytelling through digital media',
    ],
    images: [],
  },
  {
    id: 'graphic-design',
    title: 'Graphic Designing',
    emoji: '🎨',
    planet: 'Chromanova',
    planetColor: '#c084fc',
    planetRing: '#e9d5ff',
    subtitle: 'Where creativity found its canvas',
    description:
      'Before code, there was color. Designing posters for college events, creating brand identities, mastering Photoshop and Canva — this era taught me that great design is about solving problems beautifully.',
    color: '#c084fc',
    gradientFrom: '#7c3aed',
    gradientTo: '#c084fc',
    achievements: [
      'Designed event posters and promotional materials',
      'Created brand identities for college clubs',
      'Mastered tools like Photoshop and Canva',
      'Developed an eye for UI/UX aesthetics',
    ],
    images: [],
  },
  {
    id: 'coding-journey',
    title: 'Coding Journey',
    emoji: '💻',
    planet: 'Syntaxia',
    planetColor: '#06b6d4',
    subtitle: 'Hello, World! — and everything after',
    description:
      "The moment I wrote my first line of code, everything changed. From HTML pages to full-stack applications, JavaScript became my language, React my canvas, and Node.js my engine.",
    color: '#22d3ee',
    gradientFrom: '#0891b2',
    gradientTo: '#22d3ee',
    achievements: [
      'Mastered the MERN Stack (MongoDB, Express, React, Node.js)',
      'Built Firebird Airlines — a premium booking platform',
      'Created Ship Inventory Management System',
      'Explored Python, ML, and data science',
    ],
    images: [],
  },
  {
    id: 'hackathons',
    title: 'Hackathon Era',
    emoji: '🏆',
    planet: 'Velocitas',
    planetColor: '#f97316',
    subtitle: '48 hours. No sleep. Pure innovation.',
    description:
      "Hackathons were where theory met reality under extreme time pressure. Building functional prototypes in 24-48 hours, pitching to judges — these experiences taught me to think fast and ship faster.",
    color: '#fb923c',
    gradientFrom: '#ea580c',
    gradientTo: '#fb923c',
    achievements: [
      'Participated in multiple hackathons',
      'Built prototypes under extreme time pressure',
      'Pitched ideas to industry judges',
      'Learned rapid prototyping and MVP development',
    ],
    images: [],
  },
  {
    id: 'internships',
    title: 'Internship Era',
    emoji: '🚀',
    planet: 'Launchpad',
    planetColor: '#14b8a6',
    subtitle: 'First taste of the real world',
    description:
      'Internships at HCL Technologies and OpenText were where classroom knowledge met industry reality. Building ML models for healthcare data and working on enterprise software taught me how real teams operate.',
    color: '#2dd4bf',
    gradientFrom: '#0d9488',
    gradientTo: '#2dd4bf',
    achievements: [
      'HCL Technologies — Built ML models (Random Forest, SVM) for healthcare data',
      'OpenText — Contributed to enterprise software with Java, TestNG, Cucumber',
      'Learned Agile methodologies and professional practices',
      'First experience with CI/CD pipelines and automated testing',
    ],
    images: [],
  },
  {
    id: 'redhat',
    title: 'Red Hat Journey',
    emoji: '🎩',
    planet: 'Fedorium',
    planetColor: '#ef4444',
    planetRing: '#fca5a5',
    subtitle: 'From intern to Software Engineer at the open source giant',
    description:
      "Joining Red Hat's Ansible organization and growing into a Software Engineer has been the most transformative chapter. Working on tools used by thousands — vscode-ansible, ansible-lint, hashicorp.terraform — this is where I became a real engineer.",
    color: '#ef4444',
    gradientFrom: '#dc2626',
    gradientTo: '#f87171',
    achievements: [
      'Software Engineer in Ansible Org, Content Integration Team',
      'Built Terraform plan & output modules for hashicorp.terraform',
      'Contributed to vscode-ansible — webviews, WSL testing, ansible-creator',
      'Worked on ansible-lint, Konflux/Tekton CI, bootc container automation',
    ],
    images: [],
  },
  {
    id: 'open-source',
    title: 'Open Source',
    emoji: '🌍',
    planet: 'Opensphera',
    planetColor: '#22c55e',
    subtitle: 'Code without borders',
    description:
      'Open source is not just my job — it\'s a philosophy. My code in vscode-ansible, ansible-lint, and Terraform collections is used by developers across the globe. Every contribution shapes me into a better engineer.',
    color: '#4ade80',
    gradientFrom: '#16a34a',
    gradientTo: '#4ade80',
    achievements: [
      'Core contributions to vscode-ansible extension used by thousands',
      'Wrote modules for hashicorp.terraform Ansible collection',
      'Contributed to ansible-lint — improving developer experience',
      'Enabled WSL environment testing for vscode-ansible',
    ],
    images: [],
  },
  {
    id: 'devconf',
    title: 'Public Speaking',
    emoji: '🎤',
    planet: 'Resonance',
    planetColor: '#f43f5e',
    subtitle: 'From stage fright to spotlight',
    description:
      'DevConf stage. "Automate Issue Triage Using AI — From Chaos to Clarity in Seconds." The defining moment. Public speaking transformed from a fear into a passion.',
    color: '#f43f5e',
    gradientFrom: '#e11d48',
    gradientTo: '#fb7185',
    achievements: [
      'DevConf 2025 Speaker — "Automate Issue Triage Using AI"',
      'Demonstrated live AI-powered issue classification on stage',
      'Engaged with the open source community on AI + DevOps',
      'Inspired peers to explore AI-driven automation',
    ],
    images: [],
  },
  {
    id: 'ai-ml',
    title: 'AI & ML',
    emoji: '🤖',
    planet: 'Neuronis',
    planetColor: '#8b5cf6',
    planetRing: '#c4b5fd',
    subtitle: 'From automation to intelligence',
    description:
      'AI Issue Triage classifies GitHub issues in seconds. FlowForge converts natural language into executable workflows. AI has become my force multiplier.',
    color: '#a78bfa',
    gradientFrom: '#7c3aed',
    gradientTo: '#a78bfa',
    achievements: [
      'Built AI Issue Triage — automated GitHub issue classification using LLMs',
      'Created FlowForge — NL-to-workflow automation with Claude',
      'Exploring RAG, Agentic AI, and MCP for next-gen dev tools',
      'Applied ML at HCL for healthcare data analysis',
    ],
    images: [],
  },
  {
    id: 'devops-cloud',
    title: 'DevOps & Cloud',
    emoji: '☁️',
    planet: 'Nimbus',
    planetColor: '#06b6d4',
    subtitle: 'Infrastructure as code, deployment as art',
    description:
      'From Ansible playbooks to Kubernetes orchestration, building bootc container images, setting up CI/CD with Tekton — great software is only as good as its delivery pipeline.',
    color: '#22d3ee',
    gradientFrom: '#0891b2',
    gradientTo: '#22d3ee',
    achievements: [
      'Ansible, Terraform, Docker, Podman — infrastructure automation',
      'Built bootc container workflows with cloud-init and Quadlet',
      'CI/CD with Tekton, Konflux, GitHub Actions, and Jenkins',
      'Working towards AWS Solutions Architect certification',
    ],
    images: [],
  },
  {
    id: 'projects',
    title: 'Projects & Creations',
    emoji: '💡',
    planet: 'Inventum',
    planetColor: '#f97316',
    planetRing: '#fdba74',
    subtitle: 'Ideas turned into reality',
    description:
      'FlowForge, AI Issue Triage, Terraform modules — every project tells a story of a problem that needed solving. Building things people actually use is the most rewarding part.',
    color: '#fb923c',
    gradientFrom: '#ea580c',
    gradientTo: '#fb923c',
    achievements: [
      'FlowForge — AI-powered workflow automation (Django + React + Claude)',
      'AI Issue Triage — LLM-based GitHub issue classifier',
      'hashicorp.terraform modules — plan & output',
      'Load testing framework with Locust',
    ],
    images: [],
  },
  {
    id: 'beyond-code',
    title: 'Beyond Code',
    emoji: '✨',
    planet: 'Serenova',
    planetColor: '#ec4899',
    subtitle: 'The human behind the engineer',
    description:
      "Automating everything so I have more time to watch Friends, hitting the gym, exploring new cuisines — life beyond code keeps me grounded. The best ideas often come when you step away from the keyboard.",
    color: '#e879f9',
    gradientFrom: '#a855f7',
    gradientTo: '#e879f9',
    achievements: [
      'Fitness enthusiast — gym is the best debugger',
      'Home chef — cooking is just following a recipe (like code!)',
      'Friends superfan — could have a conversation entirely in quotes',
      'Believer in work-life balance and continuous self-improvement',
    ],
    images: [],
  },
  {
    id: 'travel',
    title: 'Travel & Explore',
    emoji: '🌏',
    planet: 'Wanderlust',
    planetColor: '#0ea5e9',
    planetRing: '#7dd3fc',
    subtitle: 'The world is a codebase waiting to be explored',
    description:
      'Every new city is a new perspective, every journey a new story. Traveling has taught me to adapt, to see the bigger picture, and to appreciate the diversity of ideas and cultures that make this world beautiful. The best debugging happens on a mountaintop.',
    color: '#38bdf8',
    gradientFrom: '#0284c7',
    gradientTo: '#38bdf8',
    achievements: [
      'Explored new cities, cultures, and cuisines',
      'Found inspiration for projects in unexpected places',
      'Built resilience through solo and group adventures',
      'Learned that the best ideas come from new experiences',
    ],
    images: [],
  },
];
